site_name: Hướng dẫn sử dụng hệ thống vERP

nav:
    - 'Trang chủ': 'index.md'
    - 'Nhân sự': 
        - 'Giới thiệu về phân hệ Quản lý nhân sự': 'hrm/introduction.md'
        - 'Thiết lập và khai báo ban đầu': 'hrm/initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'hrm/abbreviations.md'
        - 'Hướng dẫn sử dụng chức năng':
            - 'Khai báo danh mục': 'hrm/master-datas.md'
            - 'Tuyển dụng': 'hrm/recruitment.md'
            - 'Nhân viên': 'hrm/employee.md'
            # - 'Hợp đồng':
            # - 'Yêu cầu chấm công':
            # - 'Chấm công':
            # - 'Tiền lương':
        - 'Lịch sử phát triển sản phẩm': 'hrm/log-histories.md'
    - 'Release Notes': 'release-notes.md'
theme: readthedocs